project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html" 
        - text: "Hands-on Exercise 5"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6a"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06a.html"
        - text: "Hands-on Exercise 6b"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06b.html"
        - text: "Hands-on Exercise 6c"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06c.html"
        - text: "Hands-on Exercise 6d"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06d.html"
        - text: "Hands-on Exercise 6e"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06e.html"
        - text: "Hands-on Exercise 7a"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07a.html"
        - text: "Hands-on Exercise 7b"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07b.html"
        - text: "Hands-on Exercise 8a"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08a.html"
        - text: "Hands-on Exercise 8b"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08b.html"
        - text: "Hands-on Exercise 8c"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08c.html"
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-class Exercise 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Exercise 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-class Exercise 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

